export const brazilianDishNames: string[] = [
  "Feijoada",
  "Moqueca Baiana",
  "Pão de Queijo",
  "Coxinha",
  "Brigadeiro",
  "Vatapá",
  "Acarajé",
  "Churrasco",
  "Farofa",
  "Arroz Carreteiro",
  "Galinhada",
  "Canjica",
  "Cuscuz Paulista",
  "Bobó de Camarão",
  "Barreado",
  "Tacacá",
  "Tutu de Feijão",
  "Empadão Goiano",
  "Quindim",
  "Beijinho",
];
